<?xml version="1.0" encoding="utf-8"?><Database Name="StoreDB" Class="StoreDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=izhaksqlserver.database.windows.net;Initial Catalog=StoreDB;User ID=Amir" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="StoreDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserFirstName" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="UserLastName" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Mail" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Passwords" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Computers" Member="Computers">
    <Type Name="Computer">
      <Column Name="ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProductName" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Company" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Brand" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Price" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Photo" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Fridge" Member="Fridges">
    <Type Name="Fridge">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Company" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ProductName" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Brand" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Price" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Photo" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tv" Member="Tvs">
    <Type Name="Tv">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductName" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Company" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Brand" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Price" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Size" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Photo" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Phons" Member="Phons">
    <Type Name="Phon">
      <Column Name="ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProductName" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Company" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Brand" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Price" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Photo" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
</Database>